.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2015 Johan Wermensjö <johanwermensjoe@gmail.com>,
.\"
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH GBP-HELPER 1 "October 24, 2015"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
gbp-helper \- is a helper script to build debian packages with git
.SH SYNOPSIS
.B gbp-helper
.RI [ options ]
[\fB\-\-config\fR \fICONFIG_FILE\fR]
[<\fBcommand\fR>]
[\fIGIT_PATH\fR]
.SH DESCRIPTION
This manual page documents briefly the
.B gbp-helper
command.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
\fBgbp-helper\fP is helper script to build debian packages with git.
The script uses config files to specify branch names etc.
for your projects and helps you maintain three core branches:
release (for upstream dev), upstream and debian (for package).
.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
For a complete description, see the Info files.
.TP
.B \-h ", " \-\-help
Shows the help menu.
.TP
.B \-V ", " \-\-version
Shows the current version number.
.TP
.B \-v ", " \-\-verbose | \-q ", " \-\-quiet
Enables verbose or quiet mode.
.TP
.B \-c ", " \-\-color
Enables colored output.
.TP
.B \-s ", " \-\-safemode
Prevents any file changes.
.TP
.B \-\-config \fICONFIG_FILE\fR
Sets path to the config file (defaults to ./gbp\-helper).

.SH COMMANDS
.TP
.B commit\-release
Commits the current release to the upstream branch and tag.
Merges the created upstream with the debian branch.
.TP
.B test\-release
Prepares a release and builds the package
but leaves repository unchanged.
.TP
.B update\-changelog
Updates the changelog for a new release and commits the changes.
.TP
.B build\-pkg
Builds the latest debian package but does not tag.
.TP
.B commit\-pkg
Builds the latest debian package and tags it.
.TP
.B upload
Uploads the last build to the configured PPA.
.TP
.B create\-config
Creates an example config file.
